<?php  //[STAMP] e0a115982e95d646d7e0156e19a61e4a
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
	/**
	 * @return \Codeception\Scenario
	 */
	abstract protected function getScenario();
}
